// <auto-generated />
using System;
using CountryProject.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CountryProject.Migrations
{
    [DbContext(typeof(CountryDataContext))]
    [Migration("20200611112729_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CountryProject.Storage.Entity.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Area")
                        .HasColumnType("float");

                    b.Property<Guid?>("FaithId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Mainland")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PolityId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FaithId");

                    b.HasIndex("PolityId");

                    b.ToTable("countries");
                });

            modelBuilder.Entity("CountryProject.Storage.Entity.Faith", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("faiths");
                });

            modelBuilder.Entity("CountryProject.Storage.Entity.Polity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("polities");
                });

            modelBuilder.Entity("CountryProject.Storage.Entity.Country", b =>
                {
                    b.HasOne("CountryProject.Storage.Entity.Faith", "faith")
                        .WithMany("Country")
                        .HasForeignKey("FaithId");

                    b.HasOne("CountryProject.Storage.Entity.Polity", "Polity")
                        .WithMany("Country")
                        .HasForeignKey("PolityId");
                });
#pragma warning restore 612, 618
        }
    }
}
